# Generated by Django 4.0.3 on 2022-03-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
    ]
